import React, { useState, useContext } from 'react';
import { NavLink } from 'react-router-dom';
import {
  SparklesIcon,
  DashboardIcon,
  ChartBarIcon,
  BellIcon,
} from '../components/icons';
import { AppDataContext } from '../App';
import { Competitor, SWOTAnalysis } from '../types';
import { generateSWOTAnalysis, generateSummaryDashboard, generateMarketTrendsAnalysis, generateStrategicRecommendations } from '../services/geminiService';


const insightsNavigation: Record<string, { label: string; description: string; icon: React.ComponentType<{ className?: string }>; }> = {
    summaryInsights: {
        label: "Summary Dashboard",
        description: "Quick overview of competitor activities and highlights",
        icon: DashboardIcon,
    },
    competitorUpdates: {
        label: "Competitor Updates",
        description: "Generate a report on recent competitor activities or market topics.",
        icon: SparklesIcon,
    },
    marketTrends: {
        label: "Market Trends",
        description: "Analyze overall industry patterns and emerging opportunities",
        icon: ChartBarIcon,
    },
    aiSWOT: {
        label: "AI SWOT Insights",
        description: "Strengths, weaknesses, opportunities, and threats generated by AI",
        icon: SparklesIcon,
    },
    alerts: {
        label: "Alerts & Notifications",
        description: "Important competitor moves flagged by AI",
        icon: BellIcon,
    },
    aiRecommendations: {
        label: "AI Recommendations",
        description: "Get AI-powered suggestions to improve your strategy",
        icon: SparklesIcon,
    },
};

const AIGeneratorView: React.FC<{
    title: string;
    hasInput?: boolean;
    inputLabel?: string;
    inputPlaceholder?: string;
    buttonText: string;
    onGenerate: (topic?: string) => Promise<string>;
    onSuccess: () => void;
}> = ({ title, hasInput = false, inputLabel, inputPlaceholder, buttonText, onGenerate, onSuccess }) => {
    const [topic, setTopic] = useState('');
    const [result, setResult] = useState('');
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);

    const handleGenerate = async (e?: React.FormEvent) => {
        if (e) e.preventDefault();
        if (isLoading || (hasInput && !topic.trim())) return;

        setIsLoading(true);
        setError(null);
        setResult('');

        try {
            const response = await onGenerate(topic);
            setResult(response);
            onSuccess(); // Increment global count on success
        } catch (err) {
            setError(err instanceof Error ? err.message : `An unknown error occurred while generating ${title}.`);
        } finally {
            setIsLoading(false);
        }
    };
    
    return (
        <div className="space-y-6">
            <form onSubmit={handleGenerate}>
                <div className="flex flex-col md:flex-row gap-4">
                    {hasInput && (
                        <input
                            id={`input-${title.replace(/\s+/g, '-')}`}
                            type="text"
                            value={topic}
                            onChange={(e) => setTopic(e.target.value)}
                            placeholder={inputPlaceholder}
                            className="flex-grow bg-slate-800/70 border border-slate-600 rounded-lg py-3 px-4 text-white leading-tight focus:outline-none focus:ring-2 focus:ring-[#06B6D4] transition-all"
                            disabled={isLoading}
                        />
                    )}
                    <button
                        type="submit"
                        disabled={isLoading || (hasInput && !topic.trim())}
                        className="flex items-center justify-center gap-2 bg-gradient-to-r from-[#3B82F6] to-[#06B6D4] text-white font-bold py-3 px-6 rounded-lg hover:opacity-90 transition-all transform hover:scale-105 disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                        {isLoading ? (
                            <>
                                <svg className="animate-spin h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                                </svg>
                                <span>Generating...</span>
                            </>
                        ) : (
                            <>
                                <SparklesIcon className="w-5 h-5" />
                                <span>{buttonText}</span>
                            </>
                        )}
                    </button>
                </div>
            </form>
            {error && <div className="bg-red-500/20 text-red-300 p-4 rounded-lg text-center">{error}</div>}
            {result && !isLoading && (
                 <div className="bg-slate-800/50 rounded-xl p-6 mt-6">
                    <h3 className="text-xl font-bold text-white mb-4">AI Insight Report: {title}</h3>
                    <div className="prose prose-invert max-w-none text-slate-300 whitespace-pre-wrap">{result}</div>
                </div>
            )}
        </div>
    );
};

const AiSwotView: React.FC<{ onSuccess: () => void }> = ({ onSuccess }) => {
    const appData = useContext(AppDataContext);
    const [selectedCompetitorId, setSelectedCompetitorId] = useState<string>('');
    const [result, setResult] = useState<SWOTAnalysis | null>(null);
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);
    
    if (!appData) return null;

    const handleGenerate = async () => {
        const competitor = appData.competitors.find(c => c.id === selectedCompetitorId);
        if (!competitor) {
            setError("Please select a competitor.");
            return;
        }
        setIsLoading(true);
        setError(null);
        setResult(null);
        try {
            const swotResult = await generateSWOTAnalysis(competitor);
            setResult(swotResult);
            onSuccess(); // Increment global count on success
        } catch (err) {
            setError(err instanceof Error ? err.message : "An unknown error occurred.");
        } finally {
            setIsLoading(false);
        }
    };
    
    const SWOTCard: React.FC<{ title: string; items: string[]; className: string }> = ({ title, items, className }) => (
        <div className={`p-4 rounded-lg ${className}`}>
            <h4 className="font-bold text-lg text-white mb-2">{title}</h4>
            <ul className="list-disc list-inside space-y-1 text-slate-200 text-sm">
                {items.map((item, i) => <li key={i}>{item}</li>)}
            </ul>
        </div>
    );

    return (
        <div className="space-y-6">
            <div className="flex flex-col md:flex-row gap-4">
                <select 
                    value={selectedCompetitorId}
                    onChange={(e) => setSelectedCompetitorId(e.target.value)}
                    className="flex-grow bg-slate-800/70 border border-slate-600 rounded-lg py-3 px-4 text-white leading-tight focus:outline-none focus:ring-2 focus:ring-[#06B6D4] transition-all"
                >
                    <option value="" disabled>Select a competitor...</option>
                    {appData.competitors.map((c: Competitor) => (
                        <option key={c.id} value={c.id}>{c.name}</option>
                    ))}
                </select>
                <button
                    onClick={handleGenerate}
                    disabled={!selectedCompetitorId || isLoading}
                    className="flex items-center justify-center gap-2 bg-gradient-to-r from-[#3B82F6] to-[#06B6D4] text-white font-bold py-3 px-6 rounded-lg hover:opacity-90 transition-all transform hover:scale-105 disabled:opacity-50 disabled:cursor-not-allowed"
                >
                   {isLoading ? 'Generating...' : 'Generate SWOT Analysis'}
                </button>
            </div>

            {error && <div className="bg-red-500/20 text-red-300 p-4 rounded-lg text-center">{error}</div>}

            {isLoading && <div className="text-center p-8"> <SparklesIcon className="w-8 h-8 mx-auto animate-pulse text-cyan-400"/> <p className="mt-2 text-slate-400">AI is analyzing...</p></div>}
            
            {result && (
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-6">
                    <SWOTCard title="Strengths" items={result.strengths} className="bg-green-600/20" />
                    <SWOTCard title="Weaknesses" items={result.weaknesses} className="bg-red-600/20" />
                    <SWOTCard title="Opportunities" items={result.opportunities} className="bg-blue-600/20" />
                    <SWOTCard title="Threats" items={result.threats} className="bg-amber-600/20" />
                </div>
            )}
        </div>
    );
};

const AlertsView: React.FC = () => (
    <div className="text-center py-16 border-2 border-dashed border-slate-700 rounded-lg">
        <BellIcon className="mx-auto h-12 w-12 text-slate-500"/>
        <h3 className="mt-2 text-xl font-medium text-white">View Your Alerts</h3>
        <p className="mt-1 text-sm text-slate-400">All important competitor updates are tracked on the main Notifications page.</p>
        <NavLink
          to="/notifications"
          className="mt-4 inline-block bg-gradient-to-r from-[#3B82F6] to-[#06B6D4] text-white font-bold py-2 px-5 rounded-lg hover:opacity-90 transition-all transform hover:scale-105"
        >
          Go to Notifications
        </NavLink>
    </div>
);


const InsightsPage: React.FC = () => {
    const [activeTab, setActiveTab] = useState('competitorUpdates');
    const appData = useContext(AppDataContext);

    const renderContent = () => {
        if (!appData) return <div className="text-center p-8">Loading application data...</div>

        const { incrementInsightsGeneratedCount, competitors, companyDetails } = appData;

        switch (activeTab) {
            case 'summaryInsights':
                return <AIGeneratorView 
                    title="Summary Dashboard"
                    buttonText="Generate Summary"
                    onGenerate={() => generateSummaryDashboard(competitors)}
                    onSuccess={incrementInsightsGeneratedCount}
                />;
            case 'competitorUpdates':
                return <AIGeneratorView 
                    title="Competitor Updates"
                    hasInput
                    inputPlaceholder="e.g., 'Recent AI features from Slack'"
                    buttonText="Generate Insight"
                    onGenerate={(topic) => generateMarketTrendsAnalysis(topic || '')}
                    onSuccess={incrementInsightsGeneratedCount}
                />;
            case 'marketTrends':
                return <AIGeneratorView
                    title="Market Trends"
                    hasInput
                    inputPlaceholder="e.g., 'Future of remote collaboration software'"
                    buttonText="Analyze Trends"
                    onGenerate={(topic) => generateMarketTrendsAnalysis(topic || '')}
                    onSuccess={incrementInsightsGeneratedCount}
                />;
            case 'aiSWOT':
                return <AiSwotView onSuccess={incrementInsightsGeneratedCount} />;
            case 'alerts':
                return <AlertsView />;
            case 'aiRecommendations':
                 return <AIGeneratorView
                    title="AI Recommendations"
                    buttonText="Get Recommendations"
                    onGenerate={() => generateStrategicRecommendations(companyDetails, competitors)}
                    onSuccess={incrementInsightsGeneratedCount}
                />;
            default:
                return null;
        }
    };

    const selectedCategory = insightsNavigation[activeTab];

    return (
        <div className="space-y-8 animate-fadeInUp">
            <div>
                <h2 className="text-3xl font-bold text-white">Insights Hub</h2>
                <p className="text-slate-400 mt-1">Explore AI-powered analysis across different categories to gain a competitive edge.</p>
            </div>

            <div className="flex flex-col md:flex-row gap-8">
                <aside className="md:w-1/4">
                  <nav className="space-y-1">
                    {Object.entries(insightsNavigation).map(([key, item]) => (
                      <button
                        key={key}
                        onClick={() => setActiveTab(key)}
                        className={`w-full flex items-center gap-3 px-4 py-3 rounded-lg text-left transition-colors duration-200 ${
                          activeTab === key
                            ? 'bg-blue-600/30 text-white font-semibold'
                            : 'text-gray-400 hover:bg-slate-800/60 hover:text-white'
                        }`}
                      >
                        <item.icon className="w-5 h-5 flex-shrink-0" />
                        <span>{item.label}</span>
                      </button>
                    ))}
                  </nav>
                </aside>

                <main className="flex-1 bg-slate-900/50 border border-slate-700/80 rounded-xl backdrop-blur-sm p-8">
                    <h3 className="text-2xl font-bold text-white mb-2">{selectedCategory.label}</h3>
                    <p className="text-slate-400 mb-6">{selectedCategory.description}</p>
                    {renderContent()}
                </main>
            </div>
        </div>
    );
};

export default InsightsPage;